### ISSUE TITLE
Validate bracket propagation algorithm

### ISSUE THREAD

**Issue by mockenoff** [mockenoff/elite-dodgeball#33]

**Comment by mockenoff** [comment]
Error in `_propagate_results()`:

```
Traceback (most recent call last):
  File "/Users/timothypoon/.pyenv/versions/elite-dodgeball/lib/python3.5/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/timothypoon/.pyenv/versions/elite-dodgeball/lib/python3.5/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/timothypoon/.pyenv/versions/elite-dodgeball/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/timothypoon/.pyenv/versions/elite-dodgeball/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/mockenoff/elite-dodgeball/tourf/views.py", line 217, in games
    updated_games, updated_teams = _propagate_results(game)
  File "/mockenoff/elite-dodgeball/tourf/views.py", line 281, in _propagate_results
    next_game = game_hash[current_game.loser_to_id]
KeyError
```

**Comment by mockenoff** [comment]
https://github.com/mockenoff/elite-dodgeball/commit/06cee7f47e172b1d17493a3589714fcd4cd95334
